### ISSUE TITLE
Schedule Matching: Limited Schedules

### ISSUE THREAD

**Issue by vingkan** [scarletstudio/butterfly#100]
## Goal

Implement a generator for the matching engine that proposes matches between users who have times in their schedule where they are both available, but only for cases where one of the users has fewer than a threshold of number of total hours available, with a score for how many common hours the user with the least availability has free, so that users can meet others who they can schedule time with, even if their schedule is limited.

## Definition of Done

- The generator can be added to the matching engine and runs in production without errors.
- The generator has unit tests to confirm correctness.
- The generator produces the metadata in the format that the app and rankers expect.

## Starter Code

```
-- Implement your generator here
pipeline/matching/generators/limited_schedules.py
-- Write your unit tests here
pipeline/matching/generators/limited_schedules_test.py
```

**Comment by rbrooks6** [comment]
This is the issue you can start next! @eeerie
